version: '3.1'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: shopping_cart_db
      POSTGRES_USER: usernameMaria
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
